### ISSUE TITLE
Specify default target

### ISSUE THREAD

**Issue by eliabieri** [eliabieri/wg_display_widget_rs#1]
Specify default target (`wasm32-unknown-unknown`) in `.cargo/config.toml` as in:
```toml
[build]
target = "wasm32-unknown-unknown"
```

- [ ] Specify default target
- [ ] Update documentation
